/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsimran singh
 */

import java.awt.Font;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        Date obj=new Date();
        
        SimpleDateFormat f=new SimpleDateFormat("dd-MM-yy");
        
        String s=f.format(obj);
        
        t7.setText(s);
        t7.setEditable(false);
        y1.setEditable(false);
        
        Font font = new Font("NONE", Font.BOLD, 18);
        

        t1.setFont(font);
        t2.setFont(font);
        t3.setFont(font);
        t4.setFont(font);
        t5.setFont(font);
        t6.setFont(font);
        t7.setFont(font);
        
 
         s1.setFont(font);
        s2.setFont(font);
        s3.setFont(font);
        s4.setFont(font);
        s5.setFont(font);
        s6.setFont(font);
        s7.setFont(font);
       

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t5 = new javax.swing.JTextArea();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        sb1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        s4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        s5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        s6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        s7 = new javax.swing.JTextArea();
        sb2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("INHOUSE PROJECT MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 760, 35);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("NEW STUDENT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 120, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 180, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 240, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("SEX");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 240, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("PROJECT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 290, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("PROJECT DESCRIPTION");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 440, 200, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("DATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 670, 100, 20);
        getContentPane().add(t1);
        t1.setBounds(130, 120, 200, 30);
        getContentPane().add(t2);
        t2.setBounds(130, 170, 200, 30);
        getContentPane().add(t3);
        t3.setBounds(80, 230, 50, 30);
        getContentPane().add(t4);
        t4.setBounds(240, 230, 50, 30);

        t5.setColumns(20);
        t5.setRows(5);
        jScrollPane1.setViewportView(t5);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 290, 210, 110);
        getContentPane().add(t6);
        t6.setBounds(230, 430, 210, 200);
        getContentPane().add(t7);
        t7.setBounds(120, 660, 210, 30);

        b1.setText("REGISTER");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(150, 720, 120, 25);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("SEARCH STUDENT :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(800, 70, 300, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("NAME");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 130, 110, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(940, 120, 140, 20);
        getContentPane().add(s1);
        s1.setBounds(770, 170, 120, 40);
        getContentPane().add(s2);
        s2.setBounds(940, 170, 140, 40);

        sb1.setText("SEARCH");
        sb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb1ActionPerformed(evt);
            }
        });
        getContentPane().add(sb1);
        sb1.setBounds(1110, 180, 79, 25);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("DETAILS OF STUDENT :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(770, 240, 280, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 102));
        jLabel15.setText("AGE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(770, 290, 50, 22);
        getContentPane().add(s3);
        s3.setBounds(830, 280, 60, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setText("SEX");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(940, 290, 50, 22);
        getContentPane().add(s4);
        s4.setBounds(990, 280, 60, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 102));
        jLabel17.setText("PROJECT DESCRIPTION");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(730, 500, 200, 20);
        getContentPane().add(s5);
        s5.setBounds(930, 470, 270, 220);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 102));
        jLabel18.setText("ENROLLED DATE");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(760, 720, 160, 16);
        getContentPane().add(s6);
        s6.setBounds(920, 710, 160, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 102));
        jLabel19.setText("PROJECT");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(760, 350, 150, 20);

        s7.setColumns(20);
        s7.setRows(5);
        jScrollPane2.setViewportView(s7);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(860, 340, 270, 120);

        sb2.setText("SAVE");
        sb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb2ActionPerformed(evt);
            }
        });
        getContentPane().add(sb2);
        sb2.setBounds(1100, 710, 80, 25);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 102));
        jLabel21.setText(" TOTAL  ON THIS DAY");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(510, 470, 260, 20);
        getContentPane().add(y1);
        y1.setBounds(610, 520, 40, 30);

        jButton1.setText("SEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 520, 80, 25);

        jButton2.setText("VIEW ALL STUDENT'S");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 580, 170, 25);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, -20, 1200, 810);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(1020, 730, 110, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String a=t1.getText();
        String b=t2.getText();
        String c=t3.getText();
        String d=t4.getText();
        String e=t5.getText();
        String f=t6.getText();
        String g=t7.getText();
        
        try
        {
            
        
        db obj=new db();
        
        String qry="insert into patient values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"')";
          
        obj.update(qry);
        
        JOptionPane.showMessageDialog(null,"IT HAS BEEN UPDATED !");
        
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        
                }
        catch(Exception l)
        {
            System.out.println(l);
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void sb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb1ActionPerformed
        // TODO add your handling code here:
         
        String a=s1.getText();
        String b=s2.getText();
        
        db obj=new db();
        
        String qry= "select * from student where name='"+a+"' and id='"+b+"'";
        
        try
        {
        ResultSet rs=obj.execute(qry);
        
        if(rs.next())
        {
            String c=rs.getString("age");
            String d=rs.getString("sex");
            String e=rs.getString("projectname");
            String f=rs.getString("projectdesc");
            String h=rs.getString("date");
            
            
            
            s3.setText(c);
            s4.setText(h);
            s5.setText(e);
            s6.setText(f);
            s7.setText(d);
            
            
        }
        
        
        }
    catch(Exception p)
    {
        System.out.println(p);
    }
        
        
        
        
    }//GEN-LAST:event_sb1ActionPerformed

    private void sb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb2ActionPerformed
        // TODO add your handling code here:
        
        String a=s1.getText();
        String b=s2.getText();
        String c=s3.getText();
        String d=s4.getText();
        String e=s7.getText();
        String f=s5.getText();
        String g=s6.getText();
       
        try
        {
            
        
        db obj=new db();
        
        String qry="update student set age='"+c+"',sex='"+d+"',projectname='"+e+"',projectdesc='"+f+"',date='"+g+"' where name='"+a+"' and id='"+b+"'";
          
        obj.update(qry);
        
        JOptionPane.showMessageDialog(null,"IT HAS BEEN SAVED !");
        
        s1.setText("");
        s2.setText("");
        s3.setText("");
        s4.setText("");
        s5.setText("");
        s6.setText("");
        s7.setText("");
        
                }
        catch(Exception l)
        {
            System.out.println(l);
        }
       
    }//GEN-LAST:event_sb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Date obj=new Date();
        
        SimpleDateFormat f= new SimpleDateFormat("dd-MM-yy");
        
        String s=f.format(obj);
        
        db o=new db();
        
        String qry="select count(*) as count from student where date='"+s+"'";
        
        
        
        try {
            
            ResultSet rs=o.execute(qry);
            int n;
            if(!(rs.next()))
            {
                n=0;
            }
            else
            {
                n=rs.getInt("count");
            }
            
           
            String y=String.valueOf(n);
            
            y1.setText(y);
            
        }
        catch(Exception q)
        {
            System.out.println(q);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        view obj=new view();
        obj.setVisible(true);
        obj.setSize(1204,800);
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main obj=new main();
                obj.setVisible(true);
                 obj.setSize(1204,800);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JTextArea s7;
    private javax.swing.JButton sb1;
    private javax.swing.JButton sb2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextArea t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField y1;
    // End of variables declaration//GEN-END:variables
}
